set -g escape-time 0
set -g repeat-time 0
setw -g aggressive-resize off
set -g window-size largest

set -g prefix C-o

# Enable mouse
set -g mouse on
set -g exit-empty on
set -g window-status-seperator on

set -g default-terminal "tmux-256color"
set -g update-environment "COLORTERM"

set -as terminal-features ",tmux-256color:RGB"

set -gq utf8 on
set -gq status-utf8 on

# Window numbering base (default is 1)
set -g base-index 1

set -g 
# Customize status bar
set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"
set -g status-style "bg=green,fg=black"

# Cursor style: block, underline, or bar
set -g cursor-style bar
set -g cursor-blink on

# Scrollback history
set -g history-limit 5000

# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Prediction dimming (disable for apps like Neovim)
set -g prediction-dimming off
# Key bindings
bind-key -T prefix h split-window -h
bind-key -T prefix v split-window -v
set -g default-shell "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"

# ===========================================
# Plugins
# ===========================================
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-theme-gruvbox'
set -g @gruvbox-variant 'dark'
set -g @gruvbox-contrast 'medium'
set -g @gruvbox-show-powerline 'on'
# Initialize PPM (keep at the very bottom)
#run '~/.psmux/plugins/ppm/ppm.ps1'

